// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: cs.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoId int32

const (
	ProtoId_login_req_id        ProtoId = 1
	ProtoId_login_resp_id       ProtoId = 2
	ProtoId_create_room_req_id  ProtoId = 3
	ProtoId_create_room_resp_id ProtoId = 4
	ProtoId_open_door_req_id    ProtoId = 5
	ProtoId_open_door_resp_id   ProtoId = 6
	ProtoId_close_door_req_id   ProtoId = 7
	ProtoId_close_door_resp_id  ProtoId = 8
	ProtoId_join_room_req_id    ProtoId = 9
	ProtoId_join_room_resp_id   ProtoId = 10
)

// Enum value maps for ProtoId.
var (
	ProtoId_name = map[int32]string{
		1:  "login_req_id",
		2:  "login_resp_id",
		3:  "create_room_req_id",
		4:  "create_room_resp_id",
		5:  "open_door_req_id",
		6:  "open_door_resp_id",
		7:  "close_door_req_id",
		8:  "close_door_resp_id",
		9:  "join_room_req_id",
		10: "join_room_resp_id",
	}
	ProtoId_value = map[string]int32{
		"login_req_id":        1,
		"login_resp_id":       2,
		"create_room_req_id":  3,
		"create_room_resp_id": 4,
		"open_door_req_id":    5,
		"open_door_resp_id":   6,
		"close_door_req_id":   7,
		"close_door_resp_id":  8,
		"join_room_req_id":    9,
		"join_room_resp_id":   10,
	}
)

func (x ProtoId) Enum() *ProtoId {
	p := new(ProtoId)
	*p = x
	return p
}

func (x ProtoId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtoId) Descriptor() protoreflect.EnumDescriptor {
	return file_cs_proto_enumTypes[0].Descriptor()
}

func (ProtoId) Type() protoreflect.EnumType {
	return &file_cs_proto_enumTypes[0]
}

func (x ProtoId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ProtoId) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ProtoId(num)
	return nil
}

// Deprecated: Use ProtoId.Descriptor instead.
func (ProtoId) EnumDescriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{0}
}

type LoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *ProtoId `protobuf:"varint,1,opt,name=id,enum=main.ProtoId,def=1" json:"id,omitempty"`
}

// Default values for LoginReq fields.
const (
	Default_LoginReq_Id = ProtoId_login_req_id
)

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{0}
}

func (x *LoginReq) GetId() ProtoId {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return Default_LoginReq_Id
}

type LoginResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *ProtoId `protobuf:"varint,1,opt,name=id,enum=main.ProtoId,def=2" json:"id,omitempty"`
}

// Default values for LoginResp fields.
const (
	Default_LoginResp_Id = ProtoId_login_resp_id
)

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResp) GetId() ProtoId {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return Default_LoginResp_Id
}

type CreateRoomReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *ProtoId `protobuf:"varint,1,opt,name=id,enum=main.ProtoId,def=3" json:"id,omitempty"`
}

// Default values for CreateRoomReq fields.
const (
	Default_CreateRoomReq_Id = ProtoId_create_room_req_id
)

func (x *CreateRoomReq) Reset() {
	*x = CreateRoomReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomReq) ProtoMessage() {}

func (x *CreateRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomReq.ProtoReflect.Descriptor instead.
func (*CreateRoomReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRoomReq) GetId() ProtoId {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return Default_CreateRoomReq_Id
}

type CreateRoomResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *ProtoId `protobuf:"varint,1,opt,name=id,enum=main.ProtoId,def=4" json:"id,omitempty"`
}

// Default values for CreateRoomResp fields.
const (
	Default_CreateRoomResp_Id = ProtoId_create_room_resp_id
)

func (x *CreateRoomResp) Reset() {
	*x = CreateRoomResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoomResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResp) ProtoMessage() {}

func (x *CreateRoomResp) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResp.ProtoReflect.Descriptor instead.
func (*CreateRoomResp) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRoomResp) GetId() ProtoId {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return Default_CreateRoomResp_Id
}

type OpenDoorReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *ProtoId `protobuf:"varint,1,opt,name=id,enum=main.ProtoId,def=5" json:"id,omitempty"`
}

// Default values for OpenDoorReq fields.
const (
	Default_OpenDoorReq_Id = ProtoId_open_door_req_id
)

func (x *OpenDoorReq) Reset() {
	*x = OpenDoorReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenDoorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenDoorReq) ProtoMessage() {}

func (x *OpenDoorReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenDoorReq.ProtoReflect.Descriptor instead.
func (*OpenDoorReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{4}
}

func (x *OpenDoorReq) GetId() ProtoId {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return Default_OpenDoorReq_Id
}

type OpenDoorResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *ProtoId `protobuf:"varint,1,opt,name=id,enum=main.ProtoId,def=6" json:"id,omitempty"`
}

// Default values for OpenDoorResp fields.
const (
	Default_OpenDoorResp_Id = ProtoId_open_door_resp_id
)

func (x *OpenDoorResp) Reset() {
	*x = OpenDoorResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenDoorResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenDoorResp) ProtoMessage() {}

func (x *OpenDoorResp) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenDoorResp.ProtoReflect.Descriptor instead.
func (*OpenDoorResp) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{5}
}

func (x *OpenDoorResp) GetId() ProtoId {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return Default_OpenDoorResp_Id
}

type CloseDoorReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *ProtoId `protobuf:"varint,1,opt,name=id,enum=main.ProtoId,def=7" json:"id,omitempty"`
}

// Default values for CloseDoorReq fields.
const (
	Default_CloseDoorReq_Id = ProtoId_close_door_req_id
)

func (x *CloseDoorReq) Reset() {
	*x = CloseDoorReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseDoorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseDoorReq) ProtoMessage() {}

func (x *CloseDoorReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseDoorReq.ProtoReflect.Descriptor instead.
func (*CloseDoorReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{6}
}

func (x *CloseDoorReq) GetId() ProtoId {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return Default_CloseDoorReq_Id
}

type CloseDoorResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *ProtoId `protobuf:"varint,1,opt,name=id,enum=main.ProtoId,def=8" json:"id,omitempty"`
}

// Default values for CloseDoorResp fields.
const (
	Default_CloseDoorResp_Id = ProtoId_close_door_resp_id
)

func (x *CloseDoorResp) Reset() {
	*x = CloseDoorResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseDoorResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseDoorResp) ProtoMessage() {}

func (x *CloseDoorResp) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseDoorResp.ProtoReflect.Descriptor instead.
func (*CloseDoorResp) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{7}
}

func (x *CloseDoorResp) GetId() ProtoId {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return Default_CloseDoorResp_Id
}

type JoinRoomReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *ProtoId `protobuf:"varint,1,opt,name=id,enum=main.ProtoId,def=9" json:"id,omitempty"`
}

// Default values for JoinRoomReq fields.
const (
	Default_JoinRoomReq_Id = ProtoId_join_room_req_id
)

func (x *JoinRoomReq) Reset() {
	*x = JoinRoomReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomReq) ProtoMessage() {}

func (x *JoinRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomReq.ProtoReflect.Descriptor instead.
func (*JoinRoomReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{8}
}

func (x *JoinRoomReq) GetId() ProtoId {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return Default_JoinRoomReq_Id
}

type JoinRoomResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *ProtoId `protobuf:"varint,1,opt,name=id,enum=main.ProtoId,def=10" json:"id,omitempty"`
}

// Default values for JoinRoomResp fields.
const (
	Default_JoinRoomResp_Id = ProtoId_join_room_resp_id
)

func (x *JoinRoomResp) Reset() {
	*x = JoinRoomResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRoomResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomResp) ProtoMessage() {}

func (x *JoinRoomResp) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomResp.ProtoReflect.Descriptor instead.
func (*JoinRoomResp) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{9}
}

func (x *JoinRoomResp) GetId() ProtoId {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return Default_JoinRoomResp_Id
}

var File_cs_proto protoreflect.FileDescriptor

var file_cs_proto_rawDesc = []byte{
	0x0a, 0x08, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e,
	0x22, 0x39, 0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x71, 0x12, 0x2c, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x69, 0x64, 0x3a, 0x0c, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x5f, 0x72, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3b, 0x0a, 0x0a, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x12, 0x2d, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x5f, 0x69, 0x64, 0x3a, 0x0d, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x73,
	0x70, 0x5f, 0x69, 0x64, 0x52, 0x02, 0x69, 0x64, 0x22, 0x45, 0x0a, 0x0f, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x65, 0x71, 0x12, 0x32, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x69, 0x64, 0x3a, 0x12, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f,
	0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x47, 0x0a, 0x10, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72,
	0x65, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x69, 0x64, 0x3a,
	0x13, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x65, 0x73,
	0x70, 0x5f, 0x69, 0x64, 0x52, 0x02, 0x69, 0x64, 0x22, 0x41, 0x0a, 0x0d, 0x6f, 0x70, 0x65, 0x6e,
	0x5f, 0x64, 0x6f, 0x6f, 0x72, 0x5f, 0x72, 0x65, 0x71, 0x12, 0x30, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x5f, 0x69, 0x64, 0x3a, 0x10, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x64, 0x6f, 0x6f, 0x72,
	0x5f, 0x72, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x52, 0x02, 0x69, 0x64, 0x22, 0x43, 0x0a, 0x0e, 0x6f,
	0x70, 0x65, 0x6e, 0x5f, 0x64, 0x6f, 0x6f, 0x72, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x12, 0x31, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x69, 0x64, 0x3a, 0x11, 0x6f, 0x70, 0x65, 0x6e, 0x5f,
	0x64, 0x6f, 0x6f, 0x72, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x69, 0x64, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x43, 0x0a, 0x0e, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x64, 0x6f, 0x6f, 0x72, 0x5f, 0x72,
	0x65, 0x71, 0x12, 0x31, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x69, 0x64, 0x3a, 0x11,
	0x63, 0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x64, 0x6f, 0x6f, 0x72, 0x5f, 0x72, 0x65, 0x71, 0x5f, 0x69,
	0x64, 0x52, 0x02, 0x69, 0x64, 0x22, 0x45, 0x0a, 0x0f, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x64,
	0x6f, 0x6f, 0x72, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x5f, 0x69, 0x64, 0x3a, 0x12, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x64, 0x6f, 0x6f, 0x72,
	0x5f, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x69, 0x64, 0x52, 0x02, 0x69, 0x64, 0x22, 0x41, 0x0a, 0x0d,
	0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x65, 0x71, 0x12, 0x30, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x69, 0x64, 0x3a, 0x10, 0x6a, 0x6f, 0x69, 0x6e, 0x5f,
	0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x43, 0x0a, 0x0e, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x65, 0x73,
	0x70, 0x12, 0x31, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e,
	0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x69, 0x64, 0x3a, 0x11, 0x6a,
	0x6f, 0x69, 0x6e, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x69, 0x64,
	0x52, 0x02, 0x69, 0x64, 0x2a, 0xe9, 0x01, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x69,
	0x64, 0x12, 0x10, 0x0a, 0x0c, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x71, 0x5f, 0x69,
	0x64, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x73,
	0x70, 0x5f, 0x69, 0x64, 0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x10, 0x03, 0x12, 0x17,
	0x0a, 0x13, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x65,
	0x73, 0x70, 0x5f, 0x69, 0x64, 0x10, 0x04, 0x12, 0x14, 0x0a, 0x10, 0x6f, 0x70, 0x65, 0x6e, 0x5f,
	0x64, 0x6f, 0x6f, 0x72, 0x5f, 0x72, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x10, 0x05, 0x12, 0x15, 0x0a,
	0x11, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x64, 0x6f, 0x6f, 0x72, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x5f,
	0x69, 0x64, 0x10, 0x06, 0x12, 0x15, 0x0a, 0x11, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x64, 0x6f,
	0x6f, 0x72, 0x5f, 0x72, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x10, 0x07, 0x12, 0x16, 0x0a, 0x12, 0x63,
	0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x64, 0x6f, 0x6f, 0x72, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x69,
	0x64, 0x10, 0x08, 0x12, 0x14, 0x0a, 0x10, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x72, 0x6f, 0x6f, 0x6d,
	0x5f, 0x72, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x10, 0x09, 0x12, 0x15, 0x0a, 0x11, 0x6a, 0x6f, 0x69,
	0x6e, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x69, 0x64, 0x10, 0x0a,
}

var (
	file_cs_proto_rawDescOnce sync.Once
	file_cs_proto_rawDescData = file_cs_proto_rawDesc
)

func file_cs_proto_rawDescGZIP() []byte {
	file_cs_proto_rawDescOnce.Do(func() {
		file_cs_proto_rawDescData = protoimpl.X.CompressGZIP(file_cs_proto_rawDescData)
	})
	return file_cs_proto_rawDescData
}

var file_cs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cs_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_cs_proto_goTypes = []interface{}{
	(ProtoId)(0),           // 0: main.proto_id
	(*LoginReq)(nil),       // 1: main.login_req
	(*LoginResp)(nil),      // 2: main.login_resp
	(*CreateRoomReq)(nil),  // 3: main.create_room_req
	(*CreateRoomResp)(nil), // 4: main.create_room_resp
	(*OpenDoorReq)(nil),    // 5: main.open_door_req
	(*OpenDoorResp)(nil),   // 6: main.open_door_resp
	(*CloseDoorReq)(nil),   // 7: main.close_door_req
	(*CloseDoorResp)(nil),  // 8: main.close_door_resp
	(*JoinRoomReq)(nil),    // 9: main.join_room_req
	(*JoinRoomResp)(nil),   // 10: main.join_room_resp
}
var file_cs_proto_depIdxs = []int32{
	0,  // 0: main.login_req.id:type_name -> main.proto_id
	0,  // 1: main.login_resp.id:type_name -> main.proto_id
	0,  // 2: main.create_room_req.id:type_name -> main.proto_id
	0,  // 3: main.create_room_resp.id:type_name -> main.proto_id
	0,  // 4: main.open_door_req.id:type_name -> main.proto_id
	0,  // 5: main.open_door_resp.id:type_name -> main.proto_id
	0,  // 6: main.close_door_req.id:type_name -> main.proto_id
	0,  // 7: main.close_door_resp.id:type_name -> main.proto_id
	0,  // 8: main.join_room_req.id:type_name -> main.proto_id
	0,  // 9: main.join_room_resp.id:type_name -> main.proto_id
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_cs_proto_init() }
func file_cs_proto_init() {
	if File_cs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoomReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoomResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenDoorReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenDoorResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseDoorReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseDoorResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinRoomReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinRoomResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cs_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cs_proto_goTypes,
		DependencyIndexes: file_cs_proto_depIdxs,
		EnumInfos:         file_cs_proto_enumTypes,
		MessageInfos:      file_cs_proto_msgTypes,
	}.Build()
	File_cs_proto = out.File
	file_cs_proto_rawDesc = nil
	file_cs_proto_goTypes = nil
	file_cs_proto_depIdxs = nil
}
